name: push nuget

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    
env:
  base_version_number: "3.0.1"
  configuration: "Release"

jobs:

  build:
    runs-on: windows-latest
    timeout-minutes: 5

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Setup msbuild
      uses: microsoft/setup-msbuild@v1.0.2
      
    - name: Set version number
      id: set-version
      shell: pwsh
      run: |
        $version = "${{ env.base_version_number }}.${{ github.run_number }}${{ github.run_attempt }}"
        Write-Output "Setting version to $version"
        "VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
        "VERSION=$version" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append

    - name: Build Solution
      shell: pwsh
      run: dotnet build --configuration ${{ env.configuration }} /p:Version=${{ env.VERSION }}
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: library
        path: ${{ github.workspace }}/MediaMonkeyNet/bin/${{ env.configuration }}

    - name: Execute unit tests
      shell: pwsh
      run: dotnet test --configuration ${{ env.configuration }} --no-build

    - name: Pack nuget
      shell: pwsh
      run: |
        dotnet pack MediaMonkeyNet --configuration ${{ env.configuration }} --no-build --output "${{ github.workspace }}/publish" /p:PackageVersion=${{ env.VERSION }}

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: nuget
        path: ${{ github.workspace }}/publish

  deploy:
    if: ${{ github.event_name != 'pull_request'  && github.ref_name == 'main' }}
    environment: 'nuget'
    permissions:
      contents: none
    runs-on: windows-latest
    needs: build

    steps:
    - name: Get artifacts
      uses: actions/download-artifact@v3
      with:
        name: nuget
        path: ${{ github.workspace }}/publish

    - name: Tag commit
      uses: actions/github-script@v5
      with:
        script: |
          github.rest.git.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: 'refs/tags/${{ env.VERSION }}',
            sha: context.sha
          })

    - name: Push to NuGet
      shell: pwsh
      run: |
        Set-Location -Path '${{ github.workspace }}/publish'
        dotnet nuget push "*.nupkg" --api-key ${{ secrets.nuget_api_key }} --source https://api.nuget.org/v3/index.json

  deployX:
    permissions:
      contents: none
    runs-on: windows-latest
    needs: build

    steps:
    - name: Tag commit
      uses: actions/github-script@v5
      with:
        script: |
          github.rest.git.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: 'refs/tags/${{ steps.set-version.outputs.VERSION }}',
            sha: context.sha
          })
